### PR TITLE
GetAllVms fix

### PR DESCRIPTION
**Pull request by sergey-s-bykov**
- GetAllVms modified to do page by page VMs retrieval in multithreadi…
- Added PowerState
- PassThroughNonNull to return false instead of throwing an exception as it breaks Get-VM
- Deleted unused libraries

### CODE REVIEW

**Comment by JonKohler** [comment]
@sergey-s-bykov - Can you tune up this pull request to get these checks and such to pass? Then we can take it into the project

**Comment by sergey-s-bykov** [comment]
@JonKohler all codacy issues have been fixed.

**Comment by JonKohler** [comment]
ok great, thanks for resolving the issues - you've still got merge conflicts - can you fix those up? I literally can't merge it is as is because of them without manually fixing it

**Comment by sergey-s-bykov** [comment]
Closing this request to create a new one with resolved conflicts

**Pull request closed without merging**
